name: yesno
description: A new Flutter project.

publish_to: 'none'


version: 1.0.2+6

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.3+1
  in_app_purchase: ^3.0.6
  flutter_launcher_icons: ^0.9.3
  flutter_svg: ^1.1.0
  dio: ^4.0.6
  share_plus: ^4.0.9
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
